# Generated by Django 2.2.1 on 2019-07-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='date_added',
        ),
    ]
