# Generated by Django 2.2.1 on 2019-07-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag')),
                ('user', models.ForeignKey(default='Anon', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.UserProfile')),
            ],
        ),
    ]
