# Generated by Django 2.2.1 on 2019-07-14 12:25

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default=catalog.models.Website.default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.UserProfile'),
        ),
    ]
