# Generated by Django 2.2.1 on 2019-07-14 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190714_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
