# Generated by Django 2.2.1 on 2019-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190714_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
