# Generated by Django 2.2.1 on 2019-07-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190714_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.Tag'),
        ),
    ]
