# Generated by Django 2.2.1 on 2019-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190715_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',)},
        ),
        migrations.AddField(
            model_name='website',
            name='approved',
            field=models.BooleanField(default='False'),
        ),
    ]
