# Generated by Django 2.2.1 on 2019-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190715_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(help_text='Do not forget to add http:// or https://.'),
        ),
    ]
