# Generated by Django 2.2.1 on 2019-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190722_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='catalog.Website'),
        ),
        migrations.DeleteModel(
            name='UserAndWebsite',
        ),
    ]
